spring:
  application:
    name: song.directory
  # H2 Database Configuration
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:song_catalog
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect